web_banvemaybay/Controllers/CheckController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using web_banvemaybay.Models;
using static System.Net.WebRequestMethods;

namespace web_banvemaybay.Controllers
{
    public class CheckController : Controller
    {
        // GET: Check
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Checkve(string OTP)
        {
            string email = Session["email"].ToString();
            int mave = int.Parse(@Session["mavemuontra"].ToString());
            web_banvemaybayEntities db = new web_banvemaybayEntities();
            if (Session["otp"].ToString() == OTP)
            {
                var checkma = db.Ve.Where(c => c.IDve.Equals(mave) && c.TTlienhe.Email.Equals(email)).ToList();
                if (checkma.Count > 0)
                {
                    return View(checkma.OrderBy(c => c.IDve));
                }
                else
                {
                    ViewBag.Message = "Bạn nhập sai mã vui lòng kiểm tra lại ";
                    return RedirectToAction("xacnhan", "Check", new { thongbao = "Vui lòng kiểm kĩ Email hoặc Mã vé : " });
                }
            }
            else
            {
                ViewBag.Message = "Bạn nhập sai mã vui lòng kiểm tra lại ";
                return RedirectToAction("xacnhan", "Check", new { thongbao = "Bạn nhập sai mã otp vui lòng kiểm tra lại " });
            }
            return View();
        }
        public ActionResult LichSuVe()
        {
            string email = Session["EmailTaiKhoan"].ToString();
           
            web_banvemaybayEntities db = new web_banvemaybayEntities();
            var checkma = db.Ve.Where(c => c.TTlienhe.Email.Equals(email)).ToList();
            return View(checkma.OrderBy(c => c.IDve));
        }
        Random random = new Random();
        int otp;
        public ActionResult SendOTP()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendOTP(FormCollection form)
        {
            string mavemuontra = form["search"];
            string email = form["email"];
            otp = random.Next(100000, 10000000);

            var fromAddress = ConfigurationManager.AppSettings["FromEmailAddress"].ToString();
            var toAddress = new MailAddress(email).ToString();
            string frompass = ConfigurationManager.AppSettings["FromEmailPassword"].ToString();
            const string subject = "OTP code";
            string body = "Mã OTP: " + otp.ToString();

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress, frompass),
                Timeout = 200000
            };
            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body,
            })
            {
                smtp.Send(message);
            }
            Session["otp"] = otp.ToString();
            Session["email"] = email;
            Session["mavemuontra"] = mavemuontra;
            ViewBag.Message = "OTP đã được gửi";
            return RedirectToAction("xacnhan", "Check");
        }
        public ActionResult xacnhan(string thongbao)
        {
            ViewBag.thongbao = thongbao;
            return View();
        }


    }
}

web_banvemaybay/Controllers/HuyveController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using web_banvemaybay.Models;

namespace web_banvemaybay.Controllers
{
    public class HuyveController : Controller
    {
        // GET: Huyve
        public ActionResult Index()
        {
            web_banvemaybayEntities db = new web_banvemaybayEntities();
            int mave = int.Parse(@Session["mavemuontra"].ToString());
            ViewBag.id = mave;
            var checkma = db.Ve.Where(c => c.IDve.Equals(mave)).FirstOrDefault();
            var checkmafrom = db.Ve.Where(c => c.IDve == checkma.IDchuyenbayve).FirstOrDefault();
            ViewBag.Tenkhach = checkma.TTlienhe.FullName;
            ViewBag.NgayBay = checkma.Chuyenbay.Ngaydi.Value;
            ViewBag.dddi = checkma.Chuyenbay.Diadiemdi;
            ViewBag.ddden = checkma.Chuyenbay.Diadiemden;
            ViewBag.hang = checkma.Chuyenbay.HangHK.TenHang;
            ViewBag.macb = checkma.Chuyenbay.IDchuyenbay;
            if (checkma.Tinhtrang == "Đã thanh toán")
            {
                DateTime ngayhienhtai = DateTime.Today;
                DateTime ngayxuatphat = checkma.Chuyenbay.Ngaydi.Value;
                int sosanh = (ngayxuatphat - ngayhienhtai).Days;
                if (sosanh >= 2)
                {
                    double tienhoang;
                    tienhoang = checkma.Gia - ((30 * checkma.Gia) / 100);
                    double tienphat = checkma.Gia - tienhoang;
                    string message = "Yêu Cầu Hủy Vé";
                    checkma.Tinhtrang = message;
                    checkma.Tienphat = tienphat;
                    db.Ve.AddOrUpdate(checkma);
                    db.SaveChanges();
                    string thongbao = "Số tiền hoàng sẽ được hoàng trả trong vòng 7 ngày vui vòng liên hệ quầy bán vé gần nhất để thực hiện giải quyết";
                    var chuyenbay = db.Chuyenbay.Where(c => c.IDchuyenbay == checkma.IDchuyenbay).FirstOrDefault();
                    if (checkma.Hangve.IDhangve == 1)
                    {
                        chuyenbay.ThuongGia += 1 * checkma.Sove;
                    }
                    else
                    {
                        chuyenbay.PhoThong += 1 * checkma.Sove;
                    }
                    db.Chuyenbay.AddOrUpdate(chuyenbay);
                    db.SaveChanges();
                }
                else
                {
                    string thongbao = "Xin lỗi bạn không thể thực hiện hủy vé trong thời gian xác ngày xuất phát !!! Chỉ được thực hiện hủy vé cách thời gian xuất phát là 3 ngày";
                    ViewBag.thongbao = thongbao;
                }
               
            }
            else
            {
                string message = "Đã hủy ";
                ViewBag.Message = message;
                checkma.Tinhtrang = message;
                db.Ve.AddOrUpdate(checkma);
               db.SaveChanges();  
                var chuyenbay = db.Chuyenbay.Where(c=> c.IDchuyenbay == checkma.IDchuyenbay).FirstOrDefault();
                if (checkma.Hangve.IDhangve == 1)
                {
                    chuyenbay.ThuongGia += 1 * checkma.Sove;
                }
                else
                {
                    chuyenbay.PhoThong += 1 * checkma.Sove;
                }
                db.Chuyenbay.AddOrUpdate(chuyenbay);
                db.SaveChanges();             
            }

            if(checkma.IDchuyenbayve != null)
            {
                Session["mavefrom"] = checkma.IDchuyenbayve;
                ViewBag.idfrom = checkma.IDchuyenbayve;
                ViewBag.Tenkhachfrom = checkmafrom.TTlienhe.FullName;
                ViewBag.NgayBayfrom = checkmafrom.Chuyenbay.Ngaydi.Value;
                ViewBag.dddifrom = checkmafrom.Chuyenbay.Diadiemdi;
                ViewBag.dddenfrom = checkmafrom.Chuyenbay.Diadiemden;
                ViewBag.hangfrom = checkmafrom.Chuyenbay.HangHK.TenHang;
                ViewBag.macbfrom = checkmafrom.Chuyenbay.IDchuyenbay;
                if (checkmafrom.Tinhtrang == "Đã thanh toán")
                {
                    DateTime ngayhienhtai = DateTime.Today;
                    DateTime ngayxuatphat = checkmafrom.Chuyenbay.Ngaydi.Value;
                    int sosanh = (ngayxuatphat - ngayhienhtai).Days;
                    if (sosanh >= 3)
                    {
                        double tienhoang;
                        tienhoang = checkmafrom.Gia - ((30 * checkmafrom.Gia) / 100);
                        double tienphat = checkmafrom.Gia - tienhoang;
                        string message = "Yêu Cầu Hủy Vé";
                        checkmafrom.Tinhtrang = message;
                        checkmafrom.Tienphat = tienphat;
                        db.Ve.AddOrUpdate(checkmafrom);
                        db.SaveChanges();
                        string thongbao = "Số tiền hoàng sẽ được hoàng trả trong vòng 7 ngày vui vòng liên hệ quầy bán vé gần nhất để thực hiện giải quyết";
                        var chuyenbay = db.Chuyenbay.Where(c => c.IDchuyenbay == checkmafrom.IDchuyenbay).FirstOrDefault();
                        if (checkmafrom.Hangve.IDhangve == 1)
                        {
                            chuyenbay.ThuongGia += 1 * checkmafrom.Sove;
                        }
                        else
                        {
                            chuyenbay.PhoThong += 1 * checkmafrom.Sove;
                        }
                        db.Chuyenbay.AddOrUpdate(chuyenbay);
                        db.SaveChanges();
                    }
                    else
                    {
                        string thongbao = "Xin lỗi bạn không thể thực hiện hủy vé trong thời gian xác ngày xuất phát !!! Chỉ được thực hiện hủy vé cách thời gian xuất phát là 3 ngày";
                        ViewBag.thongbao = thongbao;
                    }

                }
                else
                {
                    string message = "Đã hủy ";
                    ViewBag.Message = message;
                    checkmafrom.Tinhtrang = message;
                    db.Ve.AddOrUpdate(checkmafrom);
                    db.SaveChanges();
                    var chuyenbay = db.Chuyenbay.Where(c => c.IDchuyenbay == checkmafrom.IDchuyenbay).FirstOrDefault();
                    if (checkmafrom.Hangve.IDhangve == 1)
                    {
                        chuyenbay.ThuongGia += 1 * checkmafrom.Sove;
                    }
                    else
                    {
                        chuyenbay.PhoThong += 1 * checkmafrom.Sove;
                    }
                    db.Chuyenbay.AddOrUpdate(chuyenbay);
                    db.SaveChanges();
                }
            }    

            

            return View();
        }
    }
}

web_banvemaybay/Views/Check/Checkve.cshtml
@using web_banvemaybay.Models;
@model IEnumerable<Ve>
@{
    ViewBag.Title = "Checkve";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div id="thongbao">
        <div class="thongbao">
            <div class="thongbao-icon">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
            <div class="thongbao-body">
                <p>Thông báo</p>
                <p class="ndtb">@ViewBag.Message</p>
            </div>
            <div class="thongbao-close">
                <i class="fa-solid fa-xmark"></i>
            </div>
        </div>
    </div>
}
else
{
    <div id="thongbao" style="display:none !important">
        <div class="thongbao">
            <div class="thongbao-icon">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
            <div class="thongbao-body">
                <p>Thông báo</p>
                <p class="ndtb"></p>

            </div>
            <div class="thongbao-close">
                <i class="fa-solid fa-xmark"></i>
            </div>
        </div>
    </div>
}
<div class="check">
    <div class="check-main">
        <div class="flight-details">
            <div class="checkve-heading">
                Chi tiết vé máy bay của bạn
            </div>
            @{
                web_banvemaybayEntities db = new web_banvemaybayEntities();
                int mave = int.Parse(@Session["mavemuontra"].ToString());
                var checkdc = db.Ve.Where(c => c.IDve == mave).FirstOrDefault();
                Session["diadiemden"] = checkdc.Chuyenbay.Diadiemden;
                foreach (var item in Model.OrderByDescending(c => c.IDve))
                {
                    <div class="checkve-body">
                        <div class="checkve-img">
                            <img src="@item.Chuyenbay.HangHK.Hinhanh" alt="">
                        </div>
                        <div class="checkve-chuyenbay">
                            <p>Mã chuyến bay: <b>@item.Chuyenbay.IDchuyenbay</b></p>
                            @if (@item.IDchuyenbayve != null)
                            {
                                <p>Chuyến bay: <b>Khứ hồi </b></p>
                            }
                            else
                            {
                                <p>Chuyến bay: <b>Một chiều </b></p>
                            }
                            <p>Hạng vé: <b>@item.Hangve.TenHangve</b> </p>
                            <p>Thời gian: <b>02h 30p</b></p>
                        </div>
                        <div class="checkve-go">
                            <p>Đi từ: <b>@item.Chuyenbay.Diadiemden</b></p>
                            <p>Cất cánh: <b>@item.Chuyenbay.Ngaydi.Value.ToString("HH:mm")</b></p>
                            <p>Ngày: <b>@item.Chuyenbay.Ngaydi.Value.ToString("dd/MM/yyyy")</b></p>
                        </div>
                        <div class="checkve-to">
                            <p>Đến: <b>@item.Chuyenbay.Diadiemdi</b></p>
                            <p>
                                Hạ cánh: <b>
                                    @item.Chuyenbay.Ngaydi.Value.AddHours(2).AddMinutes(30).ToString("HH:mm")
                                </b>
                            </p>
                            <p>
                                Ngày: <b>
                                    @item.Chuyenbay.Ngaydi.Value.AddHours(2).AddMinutes(30).ToString("dd/MM/yyyy")
                                </b>
                            </p>
                        </div>
                    </div>
                    if (item.IDchuyenbayve == null)
                    {
                        var checkma = db.Ve.Where(c => c.IDve == mave).FirstOrDefault();
                        if (checkma.Tinhtrang == "Chờ thanh toán" || checkma.Tinhtrang == "Đã thanh toán")
                        {
                            <a class="btn-huy" href="#" onclick="confirmAction()">
                                Hủy vé
                            </a>
                        }
                    }
                    <input type="hidden" name="idcu" value="@Session["idcu"]" />
                }
            }
        </div>
        @{
            foreach (var item in Model.OrderByDescending(c => c.IDve))
            {
                if (item.IDchuyenbayve != null)
                {
                    var check = db.Ve.Where(c => c.IDve == item.IDchuyenbayve).FirstOrDefault();
                    <div class="flight-details">

                        <div class="checkve-body">
                            <div class="checkve-img">
                                <img src="@check.Chuyenbay.HangHK.Hinhanh" alt="">
                            </div>
                            <div class="checkve-chuyenbay">
                                <p>Mã chuyến bay: <b>@check.Chuyenbay.IDchuyenbay</b></p>
                                <p>Chuyến bay: <b>Khứ hồi </b></p>
                                <p>Hạng vé: <b>@item.Hangve.TenHangve</b> </p>
                                <p>Thời gian: <b>02h 30p</b></p>
                            </div>
                            <div class="checkve-go">
                                <p>Đi từ: <b>@check.Chuyenbay.Diadiemden</b></p>
                                <p>Cất cánh: <b>@check.Chuyenbay.Ngaydi.Value.ToString("HH:mm")</b></p>
                                <p>Ngày: <b>@check.Chuyenbay.Ngaydi.Value.ToString("dd/MM/yyyy")</b></p>
                            </div>
                            <div class="checkve-to">
                                <p>Đến: <b>@check.Chuyenbay.Diadiemdi</b></p>
                                <p>
                                    Hạ cánh: <b>
                                        @check.Chuyenbay.Ngaydi.Value.AddHours(2).AddMinutes(30).ToString("HH:mm")
                                    </b>
                                </p>
                                <p>
                                    Ngày: <b>
                                        @check.Chuyenbay.Ngaydi.Value.AddHours(2).AddMinutes(30).ToString("dd/MM/yyyy")
                                    </b>
                                </p>
                            </div>
                        </div>
                    </div>
                    var kt = db.Ve.Where(c => c.IDve == mave).FirstOrDefault();
                    if (kt.Tinhtrang == "Chờ thanh toán" || kt.Tinhtrang == "Đã thanh toán")
                    {
                        <a class="btn-huy" style="flex:1;" href="#" onclick="confirmAction()">
                            Hủy vé
                        </a>
                    }
                }

            }
        }
    </div>

</div>
<div class="contact">
    <h1>Một số khánh sạn gần sân bay có thể bạn cần</h1>
    <div id="map" style=" width: 92%; height: 600px; margin-left: auto; margin-right: auto;"></div>
</div>
<script>
    var map;
    var service;
    var infowindow;

    function initMap() {
        infowindow = new google.maps.InfoWindow();
        // Lấy vị trí hiện tại của người dùng
        navigator.geolocation.getCurrentPosition(function (position) {
            var lat = position.coords.latitude;
            var lng = position.coords.longitude;

            var uluru = { lat: lat, lng: lng };
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 16,
                center: uluru
            });
        });
    }
    function geocodeAfterDelay() {
        setTimeout(function () {
            // Lấy địa chỉ được chọn
            var selectedAddress = "Sân bay" + " " + '@Html.Raw(Session["diadiemden"])';

            // Gọi hàm geocodeAddress với địa chỉ đã chọn
            geocodeAddress(selectedAddress);
        }, 1000);
    }
    function geocodeAddress(address) {
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({ address: address }, function (results, status) {
            if (status === 'OK') {
                var location = results[0].geometry.location;
                map.setCenter(location);

                var marker = new google.maps.Marker({
                    map: map,
                    position: location,
                    title: address
                });
                searchMap();
            } else {
                alert('Không tìm thấy địa chỉ: ' + status);
            }
        });
    }

    function searchMap() {
        var request = {
            location: map.getCenter(),
            radius: '2000',
            type: 'lodging'
        };
        service = new google.maps.places.PlacesService(map);
        service.nearbySearch(request, showPlaces);
    }
    var arrMarkers = [];

    function showPlaces(result, status) {
        if (status == google.maps.places.PlacesServiceStatus.OK && result && result.length > 0) {
            for (i in arrMarkers)
                arrMarkers[i].setMap(null);
            arrMarkers = [];
            for (i in result) {
                var place = result[i];
                var image = {
                    url: place.icon,
                    size: new google.maps.Size(71, 71),
                    origin: new google.maps.Point(0, 0),
                    anchor: new google.maps.Point(17, 34),
                    scaledSize: new google.maps.Size(25, 25),
                };
                var content = "<strong>" + place.name + "</strong><br />" +
                    "Địa chỉ: " + place.vicinity + "<br />" +
                    "Số điện thoại: " + place.phoneNumber + "<br />" +
                    "Đánh giá: " + place.rating + "/5";

                var marker = new google.maps.Marker({
                    map: map,
                    icon: image,
                    title: place.name,
                    content: content,
                    position: place.geometry.location,
                    data: place
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.setContent(this.content);
                    infowindow.open(map, this);
                    TimDuong(this.data);
                });
                arrMarkers.push(marker);
            }
        }
    }
    var ddisplay;
    function TimDuong(place) {
        var dservice = new google.maps.DirectionsService();
        if (ddisplay)
            ddisplay.setMap(null);
        ddisplay = new google.maps.DirectionsRenderer();
        ddisplay.setMap(map);

        navigator.geolocation.getCurrentPosition(function (position) {
            var userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

            var request = {
                origin: userLocation,
                destination: place.geometry.location,
                travelMode: 'WALKING',
                provideRouteAlternatives: true
            };

            dservice.route(request, function (result, status) {
                if (status == "OK") ddisplay.setDirections(result);
            });
        });
    }
    window.onload = geocodeAfterDelay;
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1atzUPfnghWgQwgXjqymZ7sSyVAD1sCI&libraries=places&callback=initMap">
</script>

<script>
function confirmAction() {
    // Sử dụng hàm `confirm` để hiển thị hộp thoại thông báo
    var confirmation = confirm("Bạn có chắc chắn muốn thực hiện hành động này?");

    // Kiểm tra kết quả của hộp thoại thông báo
    if (confirmation) {
        // Nếu người dùng chọn "Yes," thực hiện chuyển hướng
        window.location.href = "@Url.Action("Index","Huyve")";
    } else {
        // Nếu người dùng chọn "No," sử dụng URL trang hiện tại để ở lại trang cũ
        window.location.href = currentURL;
    }
}
</script>

web_banvemaybay/Views/Check/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<img src="~/Areas/Admin/ContentAdmin/image/209501.jpg" alt="" id="backgroud">
<form action="Checkve" method="post">
    <div id="main">
        <div class="TraVe">
            <div class="TraVe-heading">
                <p>Tra thông tin vé</p>
            </div>
            <div class="TraVe-content">
                <div class="locition-body-search">
                    <input type="text" name="id" id="search" placeholder="Nhập mã vé máy bay để tìm thông tin !" required class="form-control">
                    <button class="btn-search"><i class="fa-sharp fa-solid fa-magnifying-glass fa-bounce"></i></button>
                </div>
            </div>
        </div>
    </div>
</form>

web_banvemaybay/Views/Check/LichSuVe.cshtml
@using web_banvemaybay.Models;
@model IEnumerable<Ve>
@{
    ViewBag.Title = "LichSuVe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="check">
    <div class="check-main">
        <div class="flight-details">
            <div class="checkve-heading">
                Lịch sử mua vé của bạn
            </div>
            @{
                foreach (var item in Model.OrderByDescending(c => c.IDve))
                {
                    <div class="checkve-body">
                        <div class="checkve-img">
                            <img src="@item.Chuyenbay.HangHK.Hinhanh" alt="">
                        </div>
                        <div class="checkve-chuyenbay">
                            <p>Mã chuyến bay: <b>@item.Chuyenbay.IDchuyenbay</b></p>
                            @if (@item.Chuyenbay.Ngayve != null)
                            {
                                <p>Chuyến bay: <b>Khứ hồi </b></p>
                            }
                            else
                            {
                                <p>Chuyến bay: <b>Một chiều </b></p>
                            }
                            <p>Hạng vé: <b>@Session["Hangge"]</b> </p>
                            <p>Thời gian: <b>02h 30p</b></p>
                        </div>
                        <div class="checkve-go">
                            <p>Đi từ: <b>@item.Chuyenbay.Diadiemden</b></p>
                            <p>Cất cánh: <b>@item.Chuyenbay.Ngaydi.Value.ToString("HH:mm")</b></p>
                            <p>Ngày: <b>@item.Chuyenbay.Ngaydi.Value.ToString("dd/MM/yyyy")</b></p>
                        </div>
                        <div class="checkve-to">
                            <p>Đi từ: <b>@item.Chuyenbay.Diadiemdi</b></p>
                            <p>
                                Hạ cánh: <b>
                                    @if (@item.Chuyenbay.Ngayve != null)
                                    {
                                        @item.Chuyenbay.Ngayve.Value.ToString("HH:mm")
                                    }
                                    else
                                    {
                                        @item.Chuyenbay.Ngaydi.Value.AddHours(1).AddMinutes(30).ToString("HH:mm")
                                    }
                                </b>
                            </p>
                            <p>
                                Ngày: <b>
                                    @if (@item.Chuyenbay.Ngayve != null)
                                    {
                                        @item.Chuyenbay.Ngayve.Value.ToString("dd/MM/yyyy")
                                    }
                                    else
                                    {
                                        @item.Chuyenbay.Ngaydi.Value.AddHours(1).AddMinutes(30).ToString("dd/MM/yyyy")
                                    }
                                </b>
                            </p>
                        </div>
                        <div class="checkve-info">
                            <p>Mã vé: <b>@item.IDve</b></p>
                            <p>Hành khách: <b>@item.HanhKhach.Tenhanhkhach</b></p>
                            <p>Hành lý xách tay: <b>@item.Hanhli.Kg</b></p>
                            <p>Tổng tiền: <b>@String.Format("{0:0,0}", @item.Gia)đ</b></p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

web_banvemaybay/Views/Check/SendOTP.cshtml
@{
    ViewBag.Title = "SendOTP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <p>@ViewBag.Message</p>
}
<img src="~/Areas/Admin/ContentAdmin/image/209501.jpg" alt="" id="backgroud">
<form action="@Url.Action("SendOTP")" method="post">
    <div id="main">
        <div class="TraVe">
            <div class="TraVe-heading">
                <p>Tra thông tin vé</p>
            </div>
            <div class="TraVe-content">
                <div class="locition-body-search">
                    <label for="search">Mã vé:</label><input type="text" name="search" id="search" placeholder="Nhập mã vé máy bay để tìm thông tin !" required class="trave">
                    <label for="email" class="lable-otp-2">Email: </label><input type="email" name="email" required class="otp">
                    <button type="submit">Gửi mã OTP</button>
                </div>
            </div>
        </div>
    </div>
</form>

web_banvemaybay/Views/Check/xacnhan.cshtml
@{
    ViewBag.Title = "xacnhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(ViewBag.Message) || ViewBag.thongbao != null)
{
    <div id="thongbao">
        <div class="thongbao">
            <div class="thongbao-icon">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
            <div class="thongbao-body">
                <p>Thông báo</p>
                <p class="ndtb">@ViewBag.Message @ViewBag.thongbao</p>
            </div>
            <div class="thongbao-close">
                <i class="fa-solid fa-xmark"></i>
            </div>
        </div>
    </div>
}
else
{
    <div id="thongbao" style="display:none !important">
        <div class="thongbao">
            <div class="thongbao-icon">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
            <div class="thongbao-body">
                <p>Thông báo</p>
                <p class="ndtb"></p>

            </div>
            <div class="thongbao-close">
                <i class="fa-solid fa-xmark"></i>
            </div>
        </div>
    </div>
}
<img src="~/Areas/Admin/ContentAdmin/image/209501.jpg" alt="" id="backgroud">
<form action="@Url.Action("Checkve")" method="post">
    <div id="main">
        <div class="TraVe">
            <div class="TraVe-heading">
                <p>Tra thông tin vé</p>
            </div>
            <div class="TraVe-content">
                <div class="locition-body-search">
                    <label for="search">Mã vé:</label><input type="text" name="search" id="search" value="@Session["mavemuontra"]" required disabled class="trave">
                    <label for="otp" class="label-otp">OTP: </label><input type="text" name="otp" required class="otp-2">
                    <button type="submit" class="btn-search">Tra vé<i class="fa-sharp fa-solid fa-magnifying-glass fa-bounce"></i></button>
                </div>
            </div>
        </div>
    </div>
</form>